#Project: 1 Data Cleaning & Preparation

***Goal:***
Clean a raw dataset by handling
missing values, duplicates, and
incorrect data.

#Key Requirements:

• Identify missing or null values

• Remove duplicates

• Correct data formats (dates,
numbers, text)

***Key Skills:***
Data cleaning, Excel or Python
basics, data preparation

In [1]:
#Importing all the Libraries needed
import pandas as pd
import numpy as np

In [4]:
# Read the Excel sheet
df = pd.read_excel("/content/Dataset for Data Analytics(project1).xlsx")

In [7]:
#Printing an Sample Item
df.sample()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
445,ORD200445,2024-03-23,C94569,Phone,1,487.21,227 Main St,Cash,Delivered,TRK31351770,3,SAVE10,Referral,487.21

In [5]:
#Printing the Head Items i.e First 5
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [6]:
#Printing the Tail Items i.e Last 5
df.tail()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [10]:
#Printing All the Column names
a = df.columns
for i,j in enumerate(a,start=1):
  print(f"{i}. {j}")

1. OrderID
2. Date
3. CustomerID
4. Product
5. Quantity
6. UnitPrice
7. ShippingAddress
8. PaymentMethod
9. OrderStatus
10. TrackingNumber
11. ItemsInCart
12. CouponCode
13. ReferralSource
14. TotalPrice

In [11]:
#Printing the Shape and rows and colums
print(f"The Shape of the Dataset : {df.shape}\n")
print(f"No.of Rows in the Dataset : {df.shape[0]}\n")
print(f"No.of Columns of the Dataset : {df.shape[1]}\n")

The Shape of the Dataset : (1200, 14)

No.of Rows in the Dataset : 1200

No.of Columns of the Dataset : 14

In [13]:
#Printing the info of DataSet
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [23]:
print('Unique values count for each column:')
for column in df.columns:
  print(f'{column}: {df[column].nunique()}')

Unique values count for each column:
OrderID: 1200
Date: 671
CustomerID: 1189
Product: 7
Quantity: 5
UnitPrice: 1193
ShippingAddress: 655
PaymentMethod: 5
OrderStatus: 5
TrackingNumber: 1200
ItemsInCart: 10
CouponCode: 3
ReferralSource: 5
TotalPrice: 1195

In [41]:
#Finding the NULL Values Existance
df.isna().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [40]:
#Filling Null Values with i.e The column CouponCode With the text NA
df['CouponCode'] = df['CouponCode'].fillna('Not Available(NA)')
df['CouponCode'].head(10)

0               SAVE10
1               SAVE10
2             FREESHIP
3               SAVE10
4               SAVE10
5               SAVE10
6               SAVE10
7             FREESHIP
8    Not Available(NA)
9               SAVE10
Name: CouponCode, dtype: object

In [39]:
#Checking Again for the Null Values
df.isna().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [55]:
# Checking for duplicate OrderIDs
duplicate_order_ids = df[df['OrderID'].duplicated()]
print(f"Number of duplicate OrderIDs: {len(duplicate_order_ids)}")

# Checking for duplicate CustomerIDs
duplicate_customer_ids = df[df['CustomerID'].duplicated()]
print(f"Number of duplicate CustomerIDs: {len(duplicate_customer_ids)}")

Number of duplicate OrderIDs: 0
Number of duplicate CustomerIDs: 11

In [59]:
#Printing if , is there any Duplicated Values
print(df.duplicated().sum())

0

In [58]:
# Corrected date handling: Convert to datetime and keep as datetime objects
df["Date"] = pd.to_datetime(df["Date"])
print("Date column converted to datetime objects.")
display(df['Date'].head())

Date column converted to datetime objects.

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
Name: Date, dtype: datetime64[ns]

In [44]:
# Remove Extra Spaces
text_columns = [
    "Product",
    "ShippingAddress",
    "PaymentMethod",
    "OrderStatus",
    "TrackingNumber",
    "CouponCode",
    "ReferralSource"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

df.head(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,Not Available(NA),Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

In [46]:
#Checking Whether there are any extra spaced elements
for col in text_columns:
    count = (df[col].astype(str) != df[col].astype(str).str.strip()).sum()
    print(col, ":", count)

Product : 0
ShippingAddress : 0
PaymentMethod : 0
OrderStatus : 0
TrackingNumber : 0
CouponCode : 0
ReferralSource : 0

In [52]:
float_cols = df.select_dtypes(include = "float64").columns
df[float_cols] = df[float_cols].round(1)
display(df[float_cols].head())

   UnitPrice  TotalPrice
0      570.6      2853.1
1      151.4       302.7
2      550.7      2753.4
3      273.2       273.2
4      626.0      2504.0

In [54]:
#Final Check
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.6,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.1
1,ORD200001,2024-08-23,C75739,Phone,2,151.4,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.7
2,ORD200002,2024-02-27,C81728,Tablet,5,550.7,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.4
3,ORD200003,2023-10-15,C33540,Chair,1,273.2,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.2
4,ORD200004,2025-05-08,C81840,Printer,4,626.0,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.0

In [61]:
#Exporting into New File
df.to_excel("Cleaned_Dataset.xlsx", index=False)